# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/daltz/Documents/UnReal/Linux_Unreal_Engine_5.7.3

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	PPR301_FPS-Android-DebugGame  \
	PPR301_FPS-Android-Development  \
	PPR301_FPS-Android-Shipping  \
	PPR301_FPS-Linux-DebugGame  \
	PPR301_FPS-Linux-Development  \
	PPR301_FPS-Linux-Shipping  \
	PPR301_FPS-LinuxArm64-DebugGame  \
	PPR301_FPS-LinuxArm64-Development  \
	PPR301_FPS-LinuxArm64-Shipping  \
	PPR301_FPS \
	PPR301_FPSEditor-Linux-DebugGame  \
	PPR301_FPSEditor-Linux-Development  \
	PPR301_FPSEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend PPR301_FPSEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug PPR301_FPSEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

PPR301_FPS-Android-DebugGame:
	 $(BUILD) PPR301_FPS Android DebugGame  -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" $(ARGS)

PPR301_FPS-Android-Development:
	 $(BUILD) PPR301_FPS Android Development  -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" $(ARGS)

PPR301_FPS-Android-Shipping:
	 $(BUILD) PPR301_FPS Android Shipping  -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" $(ARGS)

PPR301_FPS-Linux-DebugGame:
	 $(BUILD) PPR301_FPS Linux DebugGame  -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" $(ARGS)

PPR301_FPS-Linux-Development:
	 $(BUILD) PPR301_FPS Linux Development  -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" $(ARGS)

PPR301_FPS-Linux-Shipping:
	 $(BUILD) PPR301_FPS Linux Shipping  -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" $(ARGS)

PPR301_FPS-LinuxArm64-DebugGame:
	 $(BUILD) PPR301_FPS LinuxArm64 DebugGame  -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" $(ARGS)

PPR301_FPS-LinuxArm64-Development:
	 $(BUILD) PPR301_FPS LinuxArm64 Development  -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" $(ARGS)

PPR301_FPS-LinuxArm64-Shipping:
	 $(BUILD) PPR301_FPS LinuxArm64 Shipping  -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" $(ARGS)

PPR301_FPS: PPR301_FPS-Linux-Development

PPR301_FPSEditor-Linux-DebugGame:
	 $(BUILD) PPR301_FPSEditor Linux DebugGame  -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" $(ARGS)

PPR301_FPSEditor-Linux-Development:
	 $(BUILD) PPR301_FPSEditor Linux Development  -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" $(ARGS)

PPR301_FPSEditor: PPR301_FPSEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/media/daltz/Tank/TUA_GIT/PPR301_FPS/PPR301_FPS.uproject" -Game 

.PHONY: $(TARGETS)
